<a href="https://colab.research.google.com/github/VishnuPulipaka0104/pandas01/blob/main/AI_JobMarket_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Data Manipulation using Pandas**

*Importing the Data*

In [1]:
import pandas as pd
df = pd.read_csv('/ai_job_market_insights.csv')
df

,Job_Title,Industry,Company_Size,Location,AI_Adoption_Level,Automation_Risk,Required_Skills,Salary_USD,Remote_Friendly,Job_Growth_Projection
0,Cybersecurity Analyst,Entertainment,Small,Dubai,Medium,High,UX/UI Design,111392.165243,Yes,Growth
1,Marketing Specialist,Technology,Large,Singapore,Medium,High,Marketing,93792.562466,No,Decline
2,AI Researcher,Technology,Large,Singapore,Medium,High,UX/UI Design,107170.263069,Yes,Growth
3,Sales Manager,Retail,Small,Berlin,Low,High,Project Management,93027.953758,No,Growth
4,Cybersecurity Analyst,Entertainment,Small,Tokyo,Low,Low,JavaScript,87752.922171,Yes,Decline
...,...,...,...,...,...,...,...,...,...,...
495,Data Scientist,Telecommunications,Medium,Berlin,Low,Medium,Machine Learning,105821.394046,Yes,Stable
496,Cybersecurity Analyst,Telecommunications,Small,London,Low,High,UX/UI Design,119794.992146,No,Decline
497,Cybersecurity Analyst,Energy,Large,Dubai,High,Low,UX/UI Design,79644.933099,Yes,Stable
498,Operations Manager,Healthcare,Large,Paris,High,Low,Python,77642.150625,Yes,Stable
499,HR Manager,Entertainment,Medium,Berlin,Medium,High,Project Management,68764.378921,Yes,Decline

*Columns and thier Data Types*

In [3]:
df.dtypes

Job_Title                 object
Industry                  object
Company_Size              object
Location                  object
AI_Adoption_Level         object
Automation_Risk           object
Required_Skills           object
Salary_USD               float64
Remote_Friendly           object
Job_Growth_Projection     object
dtype: object

*Number of Rows*

In [4]:
print(df.iloc[:,:].count)

<bound method DataFrame.count of                  Job_Title            Industry Company_Size   Location  \
0    Cybersecurity Analyst       Entertainment        Small      Dubai
1     Marketing Specialist          Technology        Large  Singapore
2            AI Researcher          Technology        Large  Singapore
3            Sales Manager              Retail        Small     Berlin
4    Cybersecurity Analyst       Entertainment        Small      Tokyo
..                     ...                 ...          ...        ...
495         Data Scientist  Telecommunications       Medium     Berlin
496  Cybersecurity Analyst  Telecommunications        Small     London
497  Cybersecurity Analyst              Energy        Large      Dubai
498     Operations Manager          Healthcare        Large      Paris
499             HR Manager       Entertainment       Medium     Berlin

    AI_Adoption_Level Automation_Risk     Required_Skills     Salary_USD  \
0              Medium            High        UX/UI Design  111392.165243
1              Medium            High           Marketing   93792.562466
2              Medium            High        UX/UI Design  107170.263069
3                 Low            High  Project Management   93027.953758
4                 Low             Low          JavaScript   87752.922171
..                ...             ...                 ...            ...
495               Low          Medium    Machine Learning  105821.394046
496               Low            High        UX/UI Design  119794.992146
497              High             Low        UX/UI Design   79644.933099
498              High             Low              Python   77642.150625
499            Medium            High  Project Management   68764.378921

    Remote_Friendly Job_Growth_Projection
0               Yes                Growth
1                No               Decline
2               Yes                Growth
3                No                Growth
4               Yes               Decline
..              ...                   ...
495             Yes                Stable
496              No               Decline
497             Yes                Stable
498             Yes                Stable
499             Yes               Decline

[500 rows x 10 columns]>

*Making sure the data doesn't countain any null or empty values // Data Cleansing*
looks like there are no Nan or Null values in the data.

In [5]:
df_cleaned = df.dropna(subset=['Job_Title', 'Industry', 'Company_Size', 'Location',
                               'AI_Adoption_Level', 'Automation_Risk', 'Required_Skills',
                               'Salary_USD', 'Remote_Friendly', 'Job_Growth_Projection'])
print(df_cleaned)
print(df_cleaned.iloc[:,:].count)

                 Job_Title            Industry Company_Size   Location  \
0    Cybersecurity Analyst       Entertainment        Small      Dubai
1     Marketing Specialist          Technology        Large  Singapore
2            AI Researcher          Technology        Large  Singapore
3            Sales Manager              Retail        Small     Berlin
4    Cybersecurity Analyst       Entertainment        Small      Tokyo
..                     ...                 ...          ...        ...
495         Data Scientist  Telecommunications       Medium     Berlin
496  Cybersecurity Analyst  Telecommunications        Small     London
497  Cybersecurity Analyst              Energy        Large      Dubai
498     Operations Manager          Healthcare        Large      Paris
499             HR Manager       Entertainment       Medium     Berlin

    AI_Adoption_Level Automation_Risk     Required_Skills     Salary_USD  \
0              Medium            High        UX/UI Design  111392.165243
1              Medium            High           Marketing   93792.562466
2              Medium            High        UX/UI Design  107170.263069
3                 Low            High  Project Management   93027.953758
4                 Low             Low          JavaScript   87752.922171
..                ...             ...                 ...            ...
495               Low          Medium    Machine Learning  105821.394046
496               Low            High        UX/UI Design  119794.992146
497              High             Low        UX/UI Design   79644.933099
498              High             Low              Python   77642.150625
499            Medium            High  Project Management   68764.378921

    Remote_Friendly Job_Growth_Projection
0               Yes                Growth
1                No               Decline
2               Yes                Growth
3                No                Growth
4               Yes               Decline
..              ...                   ...
495             Yes                Stable
496              No               Decline
497             Yes                Stable
498             Yes                Stable
499             Yes               Decline

[500 rows x 10 columns]
<bound method DataFrame.count of                  Job_Title            Industry Company_Size   Location  \
0    Cybersecurity Analyst       Entertainment        Small      Dubai
1     Marketing Specialist          Technology        Large  Singapore
2            AI Researcher          Technology        Large  Singapore
3            Sales Manager              Retail        Small     Berlin
4    Cybersecurity Analyst       Entertainment        Small      Tokyo
..                     ...                 ...          ...        ...
495         Data Scientist  Telecommunications       Medium     Berlin
496  Cybersecurity Analyst  Telecommunications        Small     London
497  Cybersecurity Analyst              Energy        Large      Dubai
498     Operations Manager          Healthcare        Large      Paris
499             HR Manager       Entertainment       Medium     Berlin

    AI_Adoption_Level Automation_Risk     Required_Skills     Salary_USD  \
0              Medium            High        UX/UI Design  111392.165243
1              Medium            High           Marketing   93792.562466
2              Medium            High        UX/UI Design  107170.263069
3                 Low            High  Project Management   93027.953758
4                 Low             Low          JavaScript   87752.922171
..                ...             ...                 ...            ...
495               Low          Medium    Machine Learning  105821.394046
496               Low            High        UX/UI Design  119794.992146
497              High             Low        UX/UI Design   79644.933099
498              High             Low              Python   77642.150625
499            Medium            High  Project Management   68764.378921

    Remote_Friendly Job_Growth_Projection
0               Yes                Growth
1                No               Decline
2               Yes                Growth
3                No                Growth
4               Yes               Decline
..              ...                   ...
495             Yes                Stable
496              No               Decline
497             Yes                Stable
498             Yes                Stable
499             Yes               Decline

[500 rows x 10 columns]>

Observation 1: Get all the rows where the better AI adaptation level is positively affecting the job growth prediction

In [6]:
df_new_table1 = df.loc[(df['AI_Adoption_Level'].isin(['High','Medium'])) & (df['Job_Growth_Projection'].isin(['Growth','Stable']))]
df_new_table1 = df_new_table1.sort_values(['AI_Adoption_Level','Job_Growth_Projection'])
df_new_table1

,Job_Title,Industry,Company_Size,Location,AI_Adoption_Level,Automation_Risk,Required_Skills,Salary_USD,Remote_Friendly,Job_Growth_Projection
10,Marketing Specialist,Finance,Small,London,High,High,Python,91566.973379,Yes,Growth
12,AI Researcher,Transportation,Large,San Francisco,High,Medium,Python,73151.990349,Yes,Growth
14,Product Manager,Finance,Medium,Singapore,High,High,JavaScript,101001.901141,Yes,Growth
15,Sales Manager,Telecommunications,Small,Dubai,High,Low,UX/UI Design,82799.357707,No,Growth
27,HR Manager,Manufacturing,Small,Tokyo,High,Low,Cybersecurity,73323.296331,Yes,Growth
...,...,...,...,...,...,...,...,...,...,...
468,HR Manager,Telecommunications,Medium,Dubai,Medium,High,Cybersecurity,85555.906742,Yes,Stable
478,Sales Manager,Energy,Medium,Toronto,Medium,High,Data Analysis,121444.843330,Yes,Stable
480,Marketing Specialist,Retail,Small,San Francisco,Medium,High,Python,112377.632406,No,Stable
482,Sales Manager,Finance,Large,Toronto,Medium,High,Python,84903.163239,Yes,Stable
487,HR Manager,Manufacturing,Medium,London,Medium,Medium,Sales,72017.778031,No,Stable

Observation 2: Get all the rows based on indsutry and the Job titles involved with the industry and the skills required for each job

In [8]:
df_new_table2 = df.copy()
df_new_table2['Group of Skills required'] = df.groupby(['Job_Title','Industry'])['Required_Skills'].transform(lambda x: ', '.join(x))
df_new_table2 = df_new_table2[['Job_Title','Industry','Group of Skills required']]
df_new_table2.drop_duplicates(inplace=True)
df_new_table2

,Job_Title,Industry,Group of Skills required
0,Cybersecurity Analyst,Entertainment,"UX/UI Design, JavaScript, Sales, Cybersecurity..."
1,Marketing Specialist,Technology,"Marketing, Machine Learning, Python, Marketing..."
2,AI Researcher,Technology,"UX/UI Design, UX/UI Design, Sales, JavaScript,..."
3,Sales Manager,Retail,"Project Management, JavaScript, Project Manage..."
5,UX Designer,Education,"Cybersecurity, Project Management, Project Man..."
...,...,...,...
336,Software Engineer,Education,"Project Management, Data Analysis"
342,Marketing Specialist,Transportation,JavaScript
348,Software Engineer,Energy,Project Management
351,Product Manager,Retail,Project Management
366,AI Researcher,Telecommunications,"Project Management, Sales"

How does company size impact the adoption of remote work and salaries?

In [9]:
df_new_table3 = df.groupby(['Company_Size'])[['Salary_USD', 'Remote_Friendly']].agg({'Salary_USD': 'mean', 'Remote_Friendly': 'count'})
df_new_table3 = df_new_table3.rename(columns={'Remote_Friendly': 'Count of Remote Firendly jobs'})
df_new_table3

                Salary_USD  Count of Remote Firendly jobs
Company_Size
Large         90603.503177                            166
Medium        90862.775129                            163
Small         92165.974349                            171

In [11]:
df_new_table4 = df.groupby(['AI_Adoption_Level', 'Company_Size'])['Job_Growth_Projection'].transform('count')

df_new_table4

0      54
1      65
2      65
3      59
4      59
       ..
495    61
496    59
497    47
498    47
499    60
Name: Job_Growth_Projection, Length: 500, dtype: int64

In [18]:
df_new_table5 = df[['Job_Title','Industry','Remote_Friendly', 'Salary_USD']]
df_new_table5 = df_new_table5.loc[df['Remote_Friendly'] == 'Yes']
df_new_table5 = df_new_table5.groupby(['Job_Title', 'Industry'])['Salary_USD'].mean()
df_new_table5

Job_Title      Industry
AI Researcher  Education              95648.472189
               Energy                 82792.507068
               Entertainment         114881.077917
               Finance               108572.303002
               Healthcare             92703.013895
                                         ...
UX Designer    Manufacturing          94890.275943
               Retail                 67535.165666
               Technology             78710.828034
               Telecommunications    103949.336245
               Transportation         73532.815908
Name: Salary_USD, Length: 89, dtype: float64